### ISSUE TITLE
when codes could be released ?

### ISSUE THREAD

**Issue by loujie0822** [ShannonAI/Entity-Relation-As-Multi-Turn-QA#1]
when codes could be released ?

**Comment by Refrainlhy** [comment]
+1

**Comment by ghost** [comment]
Thanks for your attention. The code will be posted about half a month later!  Please give us a few more days :-) Many thanks.

**Comment by fooSynaptic** [comment]
july means next year ;-)

**Comment by AutoAVE** [comment]
+1

**Comment by 52DL** [comment]
+1

**Comment by ChenzhengUESTC** [comment]
half a month just passed....

**Comment by wzc118** [comment]
hopefully to see the code this month!!

**Comment by ghost** [comment]
😫The dead-dead-dead-deadline was set at the end of the month. Thanks for your patience~~~~~~~

**Comment by loujie0822** [comment]
The dead-dead-dead-deadline was set at the end of the month(September) ???
