### ISSUE TITLE
Looking  forward to the code

### ISSUE THREAD

**Issue by JYZ122** [ShannonAI/Entity-Relation-As-Multi-Turn-QA#5]

**Comment by littlesulley** [comment]
Thanks for your interests in our work! we have released our code, and feel free to let us know if you have any problems. :)

**Comment by JYZ122** [comment]
Thanks to the author, the content of the training and evaluation section has not been written yet. Also, can you send me a Resume data set？Thank you


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Qinghongn Han"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月24日(星期四) 晚上10:08
收件人:&nbsp;"ShannonAI/Entity-Relation-As-Multi-Turn-QA"<Entity-Relation-As-Multi-Turn-QA@noreply.github.com&gt;;
抄送:&nbsp;"(5L8K5) 活动中心"<1710076896@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ShannonAI/Entity-Relation-As-Multi-Turn-QA] Looking  forward to the code (#5)




Thanks for your interests in our work! we have released our code, and feel free to let us know if you any problems. :)

**Comment by littlesulley** [comment]
Yes, the `training` and `evaluation` parts haven't finished but will come soon due to some changes on the interfaces. As for `RESUME`, i'm sorry that this dataset hasn't been in the recent plan of opensourcing. We'll update this repo once we opensource `RESUME`. ;)
