### ISSUE TITLE
Code for transform data to Question-Answering scheme?

### ISSUE THREAD

**Issue by TanyaZhao** [ShannonAI/Entity-Relation-As-Multi-Turn-QA#6]
Can you provide the code (utils/prep_qa_data.py) for transform data to QA scheme? 
According to your description in readme:
  
    export TASK_NAME=ace2004 
    export ORIGIN_DATA_PATH=/path/to/ace2004
    export EXPORT_DATA_PATH=/path/to/convert_qa_scheme
    cd utils/ 
    python3 prep_qa_data.py --data_sign $TASK_NAME \
	    --origin_data_path $ORIGIN_DATA_PATH \
	    --export_data_path $EXPORT_DATA_PATH 

However, there isn't the file prep_qa_data.py in utils.

Thank you!

**Comment by ArconB** [comment]
I met the same problem!

**Comment by goPikachu88** [comment]
Same issue here. Also the `./run/run_relation_extraction.py` file is missing.

**Comment by ghost** [comment]
Thanks for your issue. The repo will be updated these days.
